const langES = {
    heading: "Reaccionar Memoria Juego",
    objective: "Objetivo: Responder a las preguntas para poner a prueba tu memoria.",
    highestScore: "La puntuación más alta es",
    score: "Puntuación:",
    bestScore: "Mejor puntuación:",
    computerScore: "Puntuación de la computadora:",
    selectSymbolLabelPrompt: "Seleccione un símbolo",
    selectSymbolPrompt: "Seleccione un símbolo HTML",
    questionPrompt: "¿Ya has visto este símbolo?",
    yesPrompt: "Sí",
    noPrompt: "No",
    generalPunctuation_1: "Puntuación general 1",
    generalPunctuation_2: "Puntuación general 2",
    arrows: "Flechas",
    mathematicaloperators: "Operadores matemáticos",
    boxDrawings: "Dibujos de caja",
    blockElements: "Elementos de bloque",
    geometricShapes: "Formas geométricas",
    miscellaneousSymbols: "Símbolos varios",
    dingbats: "Dingbats",
    emoji: "Emoji",
    emojiSmileys: "Emoji Smileys",
}
export { langES };