const langCN = {
    heading: "反应记忆游戏",
    objective: "目的：回答问题来测试你的记忆力。",
    highestScore: "最高分是 ",
    score: "得分:",
    bestScore: "最佳成绩:",
    computerScore: "电脑评分:",
    selectSymbolLabelPrompt: "选择符号",
    selectSymbolPrompt: "选择HTML符号",
    questionPrompt: "你看到这个符号了吗?",
    yesPrompt: "是的",
    noPrompt: "非也。",
    generalPunctuation_1: "一般标点符号1",
    generalPunctuation_2: "一般标点符号2",
    arrows: "箭头",
    mathematicalOperators: "数学运算符",
    boxDrawings: "箱体图则",
    blockElements: "块元素",
    geometricShapes: "几何形状",
    miscellaneousSymbols: "杂项符号",
    dingbats: "丁巴茨",
    emoji: "表情符号",
    emojiSmileys: "表情表情",
}
export { langCN };